<?xml version="1.0" encoding="UTF-8"?>

<definitions
    xmlns="http://schemas.xmlsoap.org/wsdl/"
    xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/"
    xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/"
    xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="DeliveryServiceWrapper" targetNamespace="http://enterprise.netbeans.org/bpel/DeliveryServiceWrapper" xmlns:tns="http://enterprise.netbeans.org/bpel/DeliveryServiceWrapper" xmlns:plnk="http://docs.oasis-open.org/wsbpel/2.0/plnktype" xmlns:ns="http://rs.udc.es/delivery">
    <import location="DeliveryService.wsdl" namespace="http://rs.udc.es/delivery"/>
    <plnk:partnerLinkType name="DeliveryProviderLinkType">
        <plnk:role name="DeliveryProviderRole" portType="ns:DeliveryProvider"/>
    </plnk:partnerLinkType>
</definitions>
